// <auto-generated />
using Day06;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace _06.Migrations
{
    [DbContext(typeof(FishContext))]
    [Migration("20211206123902_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("Day06.Fish", b =>
                {
                    b.Property<int>("FishId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("InternalTimer")
                        .HasColumnType("INTEGER");

                    b.HasKey("FishId");

                    b.ToTable("Fishes");
                });
#pragma warning restore 612, 618
        }
    }
}
